added jikan api
camball96/aniindex pull request #4
Opened 2021-04-09 11:55 UTC by calebthecurious

Instead of using Anilist, I've added Jikan as our main API.

2021-04-09 11:56 UTC, calebthecurious commented
@camball96 @BrodZ11711 @FevoTheSicko

2021-04-09 12:01 UTC, strahinjaajvaz requested changes

2021-04-09 12:01 UTC, strahinjaajvaz commented on Index.html
>      <title>Anime</title>
The file name should be lowercase. It's convention. Please change.

2021-04-10 03:08 UTC, camball96 approved these changes

2021-04-10 03:09 UTC, camball96 approved these changes

2021-04-10 03:23 UTC, camball96 approved these changes

2021-04-10 04:52 UTC, merged